[browser]
gatherUsageStats = false

[client]
showErrorDetails = false
toolbarMode = "minimal"
showSidebarNavigation = false

[theme]
base = "dark"
primaryColor="rgb(62, 150, 170)"

[server]
enableStaticServing = true

[runner]
fastReruns = false

[logger]
level = 'info' # 'error', 'warning', 'info', or 'debug'
